#!/bin/sh

# Trying to make a better script to create a gif from image folder
# It can resize the output gif
# You need ImageMagick
#
# usage:
# makegif target_name fps file_type (resize_percentage)
#
# target_name is the name of the output file (without .gif extension)
# fps is the frames per second parameter
# file_type is the type of files the script will look for (ex: jpg, png) be careful, this is case sensitive
# resize_percentage is optionnal but resizes the output gif
#
# Example use :
# makegif mygif 24 JPG 40
# or without options
# makegif myothergif 24 png

resize=${4:="100"}

convert -resize $resize"%" -delay $2 -loop 0 "*."$3 $1".gif"





